/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  safelist: [
    'bg-slate-50/40',
    'bg-indigo-50/20',
    'bg-amber-50/20',
    'bg-violet-50/20',
    'bg-emerald-50/20',
    'bg-rose-50/20',
    'bg-slate-100/80',
    'bg-slate-100/50',
    'bg-indigo-50/60',
    'bg-amber-50/60',
    'bg-violet-50/60',
    'bg-emerald-50/60',
    'bg-rose-50/60',
    'border-slate-200/60',
    'border-slate-200/50',
    'border-indigo-100/50',
    'border-indigo-100/40',
    'border-amber-100/50',
    'border-amber-100/40',
    'border-violet-100/50',
    'border-violet-100/40',
    'border-emerald-100/50',
    'border-emerald-100/40',
    'border-rose-100/50',
    'border-rose-100/40',
    'ring-slate-400/40',
    'ring-indigo-400/40',
    'ring-amber-400/40',
    'ring-violet-400/40',
    'ring-emerald-400/40',
    'ring-rose-400/40',
    'bg-slate-500',
    'bg-indigo-600',
    'bg-amber-600',
    'bg-violet-600',
    'bg-emerald-600',
    'bg-rose-600',
  ],
  theme: {
    extend: {
      colors: {
        // ── Brand (indigo) ──
        brand: {
          50:  '#eef2ff',
          100: '#e0e7ff',
          200: '#c7d2fe',
          300: '#a5b4fc',
          400: '#818cf8',
          500: '#6366f1',
          600: '#4f46e5',
          700: '#4338ca',
          800: '#3730a3',
          900: '#312e81',
          DEFAULT:  '#6366f1',
          deep:     '#4f46e5',
          light:    '#818cf8',
          pale:     '#eef2ff',
        },
        // ── Surfaces ──
        surface: {
          DEFAULT: '#f8f9fa',
          raised:  '#f8f9fc',
          overlay: '#f1f4f9',
          sunken:  '#e8ecf4',
        },
        // ── Borders ──
        border: {
          DEFAULT: '#e2e8f0',
          strong:  '#cbd5e1',
          focus:   '#6366f1',
        },
        // ── Muted text ──
        muted: {
          DEFAULT: '#64748b',
          light:   '#94a3b8',
          xlight:  '#cbd5e1',
        },
        // ── Semantic text ──
        text: {
          primary:   '#0f172a',
          secondary: '#475569',
          tertiary:  '#94a3b8',
          disabled:  '#cbd5e1',
          inverse:   '#ffffff',
          brand:     '#6366f1',
        },
        // ── Status ──
        success: {
          50:  '#ecfdf5',
          100: '#d1fae5',
          500: '#10b981',
          600: '#059669',
          700: '#047857',
          DEFAULT: '#10b981',
        },
        warning: {
          50:  '#fffbeb',
          100: '#fef3c7',
          500: '#f59e0b',
          600: '#d97706',
          DEFAULT: '#f59e0b',
        },
        danger: {
          50:  '#fff1f2',
          100: '#ffe4e6',
          500: '#ef4444',
          600: '#dc2626',
          700: '#b91c1c',
          DEFAULT: '#ef4444',
        },
        // ── NewCareers M3 tokens (teal palette — landing + pricing) ──
        "surface-dim": "#d9dadb",
        "outline": "#72777c",
        "surface-container-low": "#f3f4f5",
        "secondary-container": "#bcebe3",
        "on-primary-container": "#00201d",
        "on-error": "#ffffff",
        "on-background": "#191c1e",
        "tertiary": "#8a9aa8",
        "on-tertiary-fixed-variant": "#3c4854",
        "secondary-fixed": "#bcebe3",
        "surface-bright": "#f8f9fa",
        "inverse-surface": "#2e3133",
        "surface-container": "#eceeef",
        "background": "#fdfdfd",
        "on-primary-fixed": "#00201d",
        "surface-container-high": "#ebedee",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#eff1f2",
        "surface-variant": "#dfe3e7",
        "on-error-container": "#410002",
        "secondary": "#49635e",
        "on-tertiary-fixed": "#121d27",
        "tertiary-container": "#d0e4f5",
        "on-secondary-container": "#00201c",
        "primary-container": "#78f2e4",
        "on-surface": "#191c1e",
        "on-surface-variant": "#41474d",
        "surface-container-highest": "#e1e5e8",
        "on-tertiary-container": "#27333e",
        "primary-fixed-dim": "#5ad5c8",
        "on-primary-fixed-variant": "#004f4a",
        "tertiary-fixed-dim": "#b5c7d8",
        "primary-fixed": "#78f2e4",
        "on-primary": "#ffffff",
        "error": "#ba1a1a",
        "on-secondary-fixed-variant": "#005047",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#d0e4f5",
        "secondary-fixed-dim": "#a1cfc7",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#00201c",
        "surface-tint": "#0d9488",
        "inverse-primary": "#5ad5c8",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#c2c7cd",
        "primary": "#0d9488",
      },
      fontFamily: {
        sans:    ['Geist', 'Inter', 'system-ui', '-apple-system', 'sans-serif'],
        display: ['Geist', 'Outfit', 'Inter', 'system-ui', 'sans-serif'],
        "headline-md": ["Geist", "sans-serif"],
        "headline-lg-mobile": ["Geist", "sans-serif"],
        "headline-xl": ["Geist", "sans-serif"],
        "display-lg-mobile": ["Geist", "Inter", "sans-serif"],
        "label-sm": ["Geist", "sans-serif"],
        "body-md": ["Geist", "sans-serif"],
        "label-md": ["Geist", "sans-serif"],
        "display-lg": ["Geist", "Inter", "sans-serif"],
        "body-lg": ["Geist", "sans-serif"],
        "headline-sm": ["Geist", "sans-serif"],
        "body-sm": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
      },
      fontSize: {
        '2xs': ['0.625rem', { lineHeight: '0.875rem' }],
        "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "1.2", "fontWeight": "700" }],
        "headline-xl": ["36px", { "lineHeight": "44px", "letterSpacing": "-0.03em", "fontWeight": "700" }],
        "display": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "display-lg-mobile": ["36px", { "lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-sm": ["12px", { "lineHeight": "1.2", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "label-md": ["14px", { "lineHeight": "1.2", "letterSpacing": "0.01em", "fontWeight": "600" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-sm": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "700" }],
      },
      spacing: {
        sidebar:             '240px',
        'sidebar-collapsed': '64px',
        topbar:              '60px',
        "margin-desktop": "40px",
        "margin": "32px",
        "base": "8px",
        "margin-mobile": "16px",
        "container-max": "1280px",
        "gutter": "24px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "stack-xl": "64px",
        "unit": "4px",
      },
      borderRadius: {
        'xs':  '0.25rem',
        'sm':  '0.375rem',
        'md':  '0.5rem',
        'lg':  '0.75rem',
        'xl':  '1rem',
        '2xl': '1.25rem',
        '3xl': '1.5rem',
        '4xl': '2rem',
        "DEFAULT": "0.25rem",
        "full": "9999px"
      },
      boxShadow: {
        'xs':         '0 1px 2px rgba(0,0,0,0.04)',
        'card':       '0 1px 3px rgba(0,0,0,0.06), 0 1px 2px rgba(0,0,0,0.04)',
        'card-hover': '0 8px 25px rgba(0,0,0,0.08), 0 2px 6px rgba(0,0,0,0.04)',
        'sm':         '0 1px 3px rgba(0,0,0,0.08)',
        'md':         '0 4px 12px rgba(0,0,0,0.06)',
        'lg':         '0 8px 24px rgba(0,0,0,0.08)',
        'xl':         '0 16px 40px rgba(0,0,0,0.10)',
        'dropdown':   '0 4px 16px rgba(0,0,0,0.08), 0 1px 4px rgba(0,0,0,0.04)',
        'modal':      '0 24px 64px rgba(0,0,0,0.12), 0 8px 16px rgba(0,0,0,0.06)',
        'glow':       '0 0 20px rgba(99,102,241,0.3)',
        'brand':      '0 4px 14px rgba(99,102,241,0.25)',
      },
      animation: {
        'fade-in':        'fadeIn 0.2s ease-out forwards',
        'slide-up':       'slideUp 0.25s cubic-bezier(0.16,1,0.3,1) forwards',
        'slide-down':     'slideDown 0.25s cubic-bezier(0.16,1,0.3,1) forwards',
        'slide-in-right': 'slideInRight 0.3s cubic-bezier(0.16,1,0.3,1) forwards',
        'scale-in':       'scaleIn 0.2s cubic-bezier(0.16,1,0.3,1) forwards',
        'spring-in':      'springIn 0.4s cubic-bezier(0.34,1.56,0.64,1) forwards',
        'shimmer':        'shimmer 1.8s ease-in-out infinite',
        'spin-slow':      'spin 2s linear infinite',
      },
      keyframes: {
        fadeIn:      { '0%': { opacity: '0' },                           '100%': { opacity: '1' } },
        slideUp:     { '0%': { transform: 'translateY(10px)',  opacity: '0' }, '100%': { transform: 'translateY(0)', opacity: '1' } },
        slideDown:   { '0%': { transform: 'translateY(-8px)', opacity: '0' }, '100%': { transform: 'translateY(0)', opacity: '1' } },
        slideInRight:{ '0%': { transform: 'translateX(100%)', opacity: '0' }, '100%': { transform: 'translateX(0)', opacity: '1' } },
        scaleIn:     { '0%': { transform: 'scale(0.95)',       opacity: '0' }, '100%': { transform: 'scale(1)',    opacity: '1' } },
        springIn:    { '0%': { transform: 'scale(0.85)',       opacity: '0' }, '100%': { transform: 'scale(1)',    opacity: '1' } },
        shimmer:     { '0%': { backgroundPosition: '-400px 0' }, '100%': { backgroundPosition: '400px 0' } },
      },
      transitionTimingFunction: {
        'spring': 'cubic-bezier(0.16, 1, 0.3, 1)',
        'smooth': 'cubic-bezier(0.4, 0, 0.2, 1)',
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms')({ strategy: 'class' }),
  ],
};
