-- ============================================================
-- V6: Enhance skill_runs for TTL caching + resume storage
-- ============================================================

-- TTL cache: evaluate = 7 days, research = 1 day, others = null (always fresh)
ALTER TABLE career_operations.skill_runs
    ADD COLUMN IF NOT EXISTS expires_at TIMESTAMPTZ;

-- Store the ATS-formatted HTML resume generated by tailor-resume skill
ALTER TABLE career_operations.skill_runs
    ADD COLUMN IF NOT EXISTS resume_html     TEXT;

-- Filename for the stored resume in Supabase storage bucket
ALTER TABLE career_operations.skill_runs
    ADD COLUMN IF NOT EXISTS resume_filename TEXT;

-- Index for TTL-aware cache lookup
-- Used by: SkillRunRepository.findValidCachedRun()
CREATE INDEX IF NOT EXISTS idx_skill_runs_cache
    ON career_operations.skill_runs (user_id, user_job_id, skill, created_at DESC)
    WHERE expires_at IS NULL OR expires_at > now();

COMMENT ON COLUMN career_operations.skill_runs.expires_at IS
    'NULL = no cache (always fresh). Set for evaluate (7d) and research (1d).';
COMMENT ON COLUMN career_operations.skill_runs.resume_html IS
    'Full ATS-formatted HTML resume from tailor-resume skill. Rendered to PDF on download.';
COMMENT ON COLUMN career_operations.skill_runs.resume_filename IS
    'Supabase storage key for the resume HTML file in application-cvs bucket.';
