package com.careerops.model;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.OffsetDateTime;
import java.util.UUID;

@Entity
@Table(name = "application_tasks")
@Getter @Setter @NoArgsConstructor @AllArgsConstructor @Builder
public class ApplicationTask {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    @Column(name = "user_job_id", nullable = false)
    private UUID userJobId;

    @Column(name = "user_id", nullable = false)
    private UUID userId;

    @Column(nullable = false)
    private String title;

    @Column
    private String description;

    @Column(name = "task_type", nullable = false)
    private String taskType = "CUSTOM";
    // CUSTOM | FOLLOW_UP | SCHEDULE_PREP | FINAL_REVIEW | RESEARCH | SUBMIT_APPLICATION

    @Column(nullable = false)
    private String priority = "MEDIUM";
    // LOW | MEDIUM | HIGH

    @Column(nullable = false)
    private String status = "PENDING";
    // PENDING | IN_PROGRESS | DONE | SKIPPED

    @Column(name = "due_date")
    private OffsetDateTime dueDate;

    @Column(name = "completed_at")
    private OffsetDateTime completedAt;

    @Column(name = "is_auto_generated", nullable = false)
    private boolean autoGenerated = false;

    @Column(name = "sort_order", nullable = false)
    private int sortOrder = 0;

    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private OffsetDateTime createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at")
    private OffsetDateTime updatedAt;
}
