package com.careerops.model;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.Instant;
import java.util.UUID;

/**
 * Task 19 — ApplicationTask entity.
 * Represents a per-job to-do item with priority and status tracking.
 */
@Entity
@Table(name = "application_tasks", schema = "career_operations",
       indexes = {
           @Index(name = "idx_app_tasks_user_due", columnList = "user_id, due_date ASC"),
           @Index(name = "idx_app_tasks_job_due", columnList = "user_job_id, due_date ASC")
       })
@Getter @Setter @NoArgsConstructor @AllArgsConstructor @Builder
public class ApplicationTask {

    @Id
    @GeneratedValue
    private UUID id;

    @Column(name = "user_job_id", nullable = false)
    private UUID userJobId;

    @Column(name = "user_id", nullable = false)
    private UUID userId;

    @Column(nullable = false, length = 500)
    private String title;

    @Column(columnDefinition = "TEXT")
    private String description;

    @Column(name = "task_type", nullable = false)
    @Builder.Default
    private String taskType = "ACTION";

    @Column(nullable = false)
    @Builder.Default
    private String priority = "MEDIUM";

    @Column(nullable = false)
    @Builder.Default
    private String status = "PENDING";

    @Column(name = "due_date")
    private Instant dueDate;

    @Column(name = "completed_at")
    private Instant completedAt;

    @Column(name = "reminder_sent")
    @Builder.Default
    private boolean reminderSent = false;

    @Column(name = "auto_generated")
    @Builder.Default
    private boolean autoGenerated = false;

    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private Instant createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at")
    private Instant updatedAt;
}
