package com.careerops.dto;

import jakarta.validation.constraints.NotNull;
import lombok.Builder;
import lombok.Data;

import java.time.Instant;
import java.util.List;
import java.util.UUID;

/**
 * DTOs for the ApplicationPlannerController.
 *
 * B2-G3 / B3 fix: ApplicationPlannerController was referencing these types
 * but the file did not exist, causing a compilation failure.
 */
public class ApplicationPlannerDtos {

    // ── Request ──────────────────────────────────────────────────────────────

    /**
     * Request body for POST /api/v1/planner/plan and /plan/async.
     * The client supplies the userJobId; userId is always taken from the JWT.
     */
    @Data
    public static class PlanRequest {

        /** The UserJob ID for which to generate the plan. */
        @NotNull(message = "userJobId is required")
        private UUID userJobId;
    }

    // ── Response ─────────────────────────────────────────────────────────────

    /**
     * Response body for synchronous and async-result plan endpoints.
     */
    @Data
    @Builder
    public static class PlanResponse {

        /** Job/UserJob ID this plan belongs to. */
        private UUID userJobId;

        /** Ordered list of generated action items. */
        private List<TaskItem> tasks;

        /** ISO-8601 timestamp of when the plan was generated. */
        private Instant generatedAt;

        /** Number of tasks generated. */
        private int taskCount;
    }

    // ── Task item embedded in PlanResponse ───────────────────────────────────

    @Data
    @Builder
    public static class TaskItem {
        private UUID    id;
        private String  title;
        private String  description;
        private String  taskType;   // ACTION | FOLLOW_UP | PREP | REVIEW | SUBMIT
        private String  priority;   // LOW | MEDIUM | HIGH | URGENT
        private String  status;     // PENDING | COMPLETED
        private Instant dueDate;
        private boolean autoGenerated;
    }

    // ── Async job status (returned via notification / polling) ────────────────

    /**
     * Lightweight status wrapper used by the in-memory job cache in
     * ApplicationPlannerService when the async result is polled via
     * GET /plan/result/{jobId}.
     */
    public enum JobStatus {
        PENDING, COMPLETED, FAILED
    }
}
