package com.careerops.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.Instant;
import java.util.List;
import java.util.UUID;

public class PlannerDTO {

    @Data @Builder @NoArgsConstructor @AllArgsConstructor
    public static class TaskResponse {
        private UUID id;
        private UUID userJobId;
        private String title;
        private String description;
        private String taskType;
        private String priority;
        private String status;
        private Instant dueDate;
        private Instant completedAt;
        private boolean autoGenerated;
        private Instant createdAt;
    }

    @Data @Builder @NoArgsConstructor @AllArgsConstructor
    public static class DeadlineResponse {
        private UUID id;
        private UUID userJobId;
        private String eventType;
        private String title;
        private Instant eventDate;
        private String notes;
        private Instant createdAt;
    }

    @Data @Builder @NoArgsConstructor @AllArgsConstructor
    public static class UpcomingResponse {
        private List<TaskResponse> pendingTasks;
        private List<TaskResponse> overdueTasks;
        private List<DeadlineResponse> upcomingEvents;
    }

    @Data @Builder @NoArgsConstructor @AllArgsConstructor
    public static class TaskCompletionResponse {
        private TaskResponse task;
        private ProgressDTO.StreakResponse streak;
    }
}
