CREATE SCHEMA IF NOT EXISTS careerops;
CREATE DOMAIN IF NOT EXISTS JSONB AS JSON;
CREATE DOMAIN IF NOT EXISTS TIMESTAMPTZ AS TIMESTAMP WITH TIME ZONE;
SET SCHEMA careerops;
CREATE DOMAIN IF NOT EXISTS JSONB AS JSON;
CREATE DOMAIN IF NOT EXISTS TIMESTAMPTZ AS TIMESTAMP WITH TIME ZONE;

CREATE TABLE IF NOT EXISTS careerops.shedlock (
    name VARCHAR(64) NOT NULL,
    lock_until TIMESTAMP NOT NULL,
    locked_at TIMESTAMP NOT NULL,
    locked_by VARCHAR(255) NOT NULL,
    PRIMARY KEY (name)
);

