CREATE SCHEMA IF NOT EXISTS careerops;
CREATE DOMAIN IF NOT EXISTS JSONB AS JSON;
CREATE DOMAIN IF NOT EXISTS TIMESTAMPTZ AS TIMESTAMP WITH TIME ZONE;
SET SCHEMA careerops;
CREATE DOMAIN IF NOT EXISTS JSONB AS JSON;
CREATE DOMAIN IF NOT EXISTS TIMESTAMPTZ AS TIMESTAMP WITH TIME ZONE;


